#+TITLE: Embedded Software Designer
#+AUTHOR: Reginald Marr
#+EMAIL: reginald.t.marr@gmail.com
#+ADDRESS: Hamilton, Ontario
#+MOBILE: 519 410 9617
#+LINKEDIN: reginald-marr-0b28a8a3
#+QUOTE: "Everything is mutable"
#+GITHUB: reggiemarr
#+STACKOVERFLOW: 3274010

#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: hidestars indent
#+LaTeX_CLASS_OPTIONS: [a4paper,ragged2e,withhyper]
#+LaTeX_HEADER: \usepackage{enumitem}
#+LaTeX_HEADER: \usepackage[default]{lato}
#+LATEX_COMPILER: xelatex

#+LATEX_CLASS: altacv
#+LATEX_HEADER: \geometry{left=0.5cm,right=9cm,marginparwidth=8.5cm,marginparsep=0.3cm,top=1.0cm,bottom=1.0cm}

#+latex: \marginpar{
* About Me
I am first and foremost most proud of my ability to collaborate with peers across a variety of disciplines (and a variety of physical locations) to produce something better than the sum of our individual contributions.

Additionally, I pride myself on my ability to grind away at complex problems, break them down, and define their atomic components.

By doing this I am able to develop robust solutions which solve not just the specific task at hand but provide adaptability to solve the problem in a general sense.

* Education

** B.Tech - [[https://www.eng.mcmaster.ca/sept/programs/degree-options/btech/automation-engineering-technology][Automation Engineering Technology]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: McMaster University
:END:
+ Capstone
  Developed G-Code Generator Cross platform application (Qt & C++) from 3D CAD models for novel metal 3D printing process.

+ Level 600 Project
  Developed a neural network and network industrial system for modeling and controlling the distillation of ethanol.

+ Completed 16 Months of Co-Op
** Adv.Dip - [[https://www.mohawkcollege.ca/programs/technology/chemical-engineering-technology-co-op-533][Chemical Engineering Technology]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: Mohawk College
:END:

** Certificate - [[https://acbsp.org/?][Business Management]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: Mohawk College
:END:

* Skills
+ Languages
    C/C++, Rust, Python, SQL, MATLAB, Elisp
+ Developer Tools
    Git, Docker, Jenkins, Jira, Ansible, Kubernetes
+ Frameworks
    threadX, freeRTOS, POSIX, Emacs, Linux

#+latex: }
* Experience

** [[https://www.l3harris.com/all-capabilities/wescam-mx-series][Embedded Software Designer - New Product Integration]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2020-01-01>
:TO:     <2022-10-24>
:LOCATION: Hamilton, Ontario
:EMPLOYER: L3Harris-Wescam
:LABEL: L3Harris
:END:

+ Designed a common driver framework which provided modular device orchestration for multiple projects.
+ Designed a python/rust framework to support automated testing and analysis of embedded systems.
+ Developed capabilities to streamline conversion of text-based documentation into PDF, Powerpoint and static website formats.
+ Collaborated across engineering disciplines to develop and refine lens and laser sub-assemblies.
+ Provided collection and analysis support during in-field flight tests.

** [[https://www.l3harris.com/all-capabilities/wescam-mx-series][Embedded Software Designer - Sustaining]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2018-05-18>
:TO:     <2019-12-31>
:LOCATION: Hamilton, Ontario
:EMPLOYER: L3Harris-Wescam
:END:

+ Provided support triaging bugs found during pre-shipment verification.
+ Acted as inter-department liaison to solve logistical issues for customer deliveries.
+ Developed automation tooling using python and web-based technologies to optimized various workflows.
+ Generated documentation and improvement proposals for legacy software components.
+ Utilized TDD best practices to develop bugfixes and improvements to legacy software.

** [[https://www.eng.mcmaster.ca/sept/practice/learning-factory][Tech Assistant (Co-Op)]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2017-05-01>
:TO:     <2017-08-31>
:LOCATION: Hamilton, Ontario
:EMPLOYER: McMaster University - The Learning Factory
:END:

+ Summarized best-in-industry practices for improvement proposals.
+ Provided estimation support for various full-scale systems.
+ Responsible for process design, DCS system integration, hardware installation, and HMI development.
+ Designed part/tool tracking system using custom RFID hardware and software developed for coordination between desktop and embedded targets via C, C#, and MySQL.

** [[https://www.directenergy.com/about/brands/airtron][Project Coordinator (Co-Op)]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2016-02-01>
:TO:     <2016-08-30>
:LOCATION: Missisauga, Ontario
:EMPLOYER: Airtron Canada
:END:

+ Designed and developed linux based relay to provide logging of environmental variables using python and custom REST API.
+ Assisted in creating a proposal for a biogas cogen to convert food and animal waste into low grade electricity and high grade heat.
+ Provided estimation support on energy services contracts involving the offset of GHG's via load balancing, HVAC system improvements, and more.
