#+TITLE: Embedded Software Developer
#+AUTHOR: Reginald Marr
#+EMAIL: reginald.t.marr@gmail.com
#+ADDRESS: Hamilton, ON
#+MOBILE: +1 519 410 9617
#+LINKEDIN: reginald-marr-0b28a8a3 "Reginald Marr"
#+SUBTITLE: "Everything is mutable"
#+GITHUB: reggiemarr
#+STACKOVERFLOW: 3274010 reggiemarr

#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: hidestars indent
#+LaTeX_CLASS_OPTIONS: [a4paper,ragged2e,withhyper]
#+LaTeX_HEADER: \usepackage{enumitem}
#+LATEX_COMPILER: xelatex

#+LATEX_CLASS: altacv
#+LATEX_HEADER: \geometry{left=1cm,right=9cm,marginparwidth=8cm,marginparsep=0.5cm,top=1.25cm,bottom=1.25cm}

#+latex: \marginpar{
* About Me
I am first and foremost most proud of my ability to collaborate with peers across a variety of disciplines (and a variety of physical locations) to produce something better than the sum of our individual contributions.

Additionally I pride myself on my ability to grind away at complex problems, break them down, and define their atomic components.

By doing this I am able to develop robust solutions which solve not just the specific task at hand but provide adaptability to solve the problem in a general sense.

* Education & Certifications

** B .Tech - [[https://www.eng.mcmaster.ca/sept/programs/degree-options/btech/automation-engineering-technology][Process Automation]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: McMaster University
:END:
+ Capstone
  Developed G-Code Generator Cross platform application (Qt & C++) from 3D CAD models for novel metal 3D printing process.

+ Level 600 Project
  Developed a neural network and network industrial system for modeling and controlling the distillation of ethanol.

+ Completed 16 Months of Co-Op
** AdvDip - [[https://www.mohawkcollege.ca/programs/technology/chemical-engineering-technology-co-op-533][Chemical Engineering Technology]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: Mohawk College
:END:

** [[https://acbsp.org/?][Certificate in Business Management]]
:PROPERTIES:
:CV_ENV: cventry
:FROM: <2013-09-01>
:TO: <2018-06-15>
:LOCATION: Hamilton, Ontario
:EMPLOYER: Mohawk College
:END:

* Skills
+ Languages
    C/C++, Rust, Python, SQL, Matlab
+ Developer Tools
    Git, Docker, Jenkins, Jira, Ansible
+ Frameworks
    threadX, freeRTOS, POSIX, Emacs

#+latex: }
* Experience

** [[https://www.l3harris.com/all-capabilities/wescam-mx-series][Embedded Software Designer - New Product Integration]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2020-01-01>
:TO:     <2022-10-24>
:LOCATION: Hamilton, Ontario
:EMPLOYER: L3Harris-Wescam
:LABEL: L3Harris
:END:

+ Designed a python/rust framework to support automated testing and analysis of MX systems.
+ Developed capabilities to streamline conversion of text-based documentation into PDF, Powerpoint and static website formats.
+ Led software development/project coordination for both NPI and sustaining.
+ Collaborated across engineering disciplines to develop and refine lens and laser sub-assembly for advanced EO products.
+ Performed collection and analysis of complex systems during in-field flight tests.

** [[https://www.l3harris.com/all-capabilities/wescam-mx-series][Embedded Software Designer - Sustaining]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2018-05-18>
:TO:     <2019-12-31>
:LOCATION: Hamilton, Ontario
:EMPLOYER: L3Harris-Wescam
:END:

+ Provided support triaging bugs found during pre-shipment verification.
+ Acted as inter-department liaison to solve logistical issues for customer deliveries.
+ Developed automation tooling using python and web-based technologies to optimized various workflows.
+ Generated documentation and improvement proposals for legacy software components.
+ Utilized TDD training to develop robust bugfixes and improvements to legacy software.

** [[https://www.eng.mcmaster.ca/sept/practice/learning-factory][Tech Assistant]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2017-05-01>
:TO:     <2017-08-31>
:LOCATION: Hamilton, Ontario
:EMPLOYER: McMaster University - The Learning Factory
:END:

+ Responsible for process design, DCS system integration, hardware installation, and HMI development.
+ Developed a product to track part/tool utilization using custom RFID hardware developing software using embedded C, C#, and MySQL.

** [[https://www.directenergy.com/about/brands/airtron][Project Coordinator]]
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2016-02-01>
:TO:     <2016-09-01>
:LOCATION: Missisauga, Ontario
:EMPLOYER: Airtron Canada
:END:

+ Designed and developed raspberry pi based relay to provide logging of environmental variables using python and custom REST API.
+ Assisted in creating a proposal for a biogas cogen to convert food and animal waste into low grade electricity and high grade heat.
+ Provided estimation support on energy services contracts involving the offset of GHG's via load balancing, HVAC system improvements, and more.
